---
- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Visual Studio Code
  package:
    name: "{{ code_package_name }}"
    state: present

