---
- name: Copy the Visual Studio Code REPO file (Debian)
  copy:
    src: "files/vscode.list"
    dest: "/etc/apt/sources.list.d/vscode.list"
  register: coderepofile

- name: Import the repo key to the RPM database (Debian)
  shell: |
    curl {{ code_repo_key_url }} | gpg --dearmor > microsoft.gpg
    sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  args:
    executable: /bin/bash
  when: coderepofile.changed

- name: Install Visual Studio Code (Debian)
  apt: 
    name: code
    update_cache: yes 

