---
- name: Copy the Visual Studio Code REPO file (RHEL)
  copy:
    src: "files/vscode.repo"
    dest: "/etc/yum.repos.d/vscode.repo"
    owner: root
    group: root
    mode: 0644
  register: coderepofile

- name: Import the repo key to the RPM database (RHEL)
  rpm_key:
    key: "{{ code_repo_key_url }}"
    state: present

