---
- name: Copy the Visual Studio Code REPO file (RHEL)
  copy:
    src: "files/vscode.repo"
    dest: "/etc/yum.repos.d/vscode.repo"
    owner: root
    group: root
    mode: 0644
  register: coderepofile

